import streamlit as st
import joblib
import re

st.set_page_config(page_title="AI vs Human Text Detector", page_icon="🤖")

# Load saved model, vectorizer, and label encoder
@st.cache_resource
def load_artifacts():
    model = joblib.load('ai_detector_model.pkl')
    vectorizer = joblib.load('tfidf_vectorizer.pkl')
    le = joblib.load('label_encoder.pkl')
    return model, vectorizer, le

model, vectorizer, le = load_artifacts()

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-z\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

st.title("🤖 AuthentiText — AI vs Human Text Detector")
st.write("Paste any text below to check whether it was likely written by a human or generated by AI.")

user_text = st.text_area("Enter text to analyze", height=200)

if st.button("Detect"):
    if user_text.strip():
        cleaned = clean_text(user_text)
        vec = vectorizer.transform([cleaned])
        pred = model.predict(vec)[0]
        label = le.inverse_transform([pred])[0]

        proba = model.predict_proba(vec)[0]
        confidence = max(proba) * 100

        if label.lower() == "human":
            st.success(f"🧑 Prediction: **{label}** ({confidence:.1f}% confidence)")
        else:
            st.error(f"🤖 Prediction: **{label}** ({confidence:.1f}% confidence)")
    else:
        st.warning("Please enter some text to analyze.")
